export const Profile = {
  idCardNo: '1461300151867',
  imageReadSmartCard: '14613XXXXX867',
  idCardType: 'บัตรประชาชน',
  titleName: 'นาย',
  firstName: 'วีรพล',
  lastName: 'สันประเดิม',
  nickName: 'กอล์ฟ',
  birthdate: '14/11/2538',
  gender: 'ชาย',
  homeNo: '10',
  buildingName: '-',
  floor: '-',
  room: '-',
  moo: '8',
  mooBan: 'บ้านหนองกุง',
  soi: '-',
  street: '-',
  tumbol: 'สมเด็จ',
  amphur: 'สมเด็จ',
  province: 'กาฬสินธุ์',
  zipCode: '46150',
  titleNameEn: 'Mr.',
  firstNameEn: 'Weerspol',
  lastNameEn: 'Sanpradaem',
  nickNameEn: 'Golf',
  issueDate: '-',
  expireDate: '-',
};


